#!/usr/bin/env node
// The Landmark Tracker records runtime (S-01T): capture a Destination Question
// Card (DQC) before any landmark, Spec or Wiki destination exists, evolve it
// without losing its origin, connect it to landmarks as they emerge, and
// rebuild the generated TRACKER.json projection from the records alone.
//
// Three rules shape it. Records are the only author: TRACKER.json is derived,
// never read back as source, and a rebuild from the same records is byte-for-
// byte identical. A write never destroys the previous valid file: every
// mutation is validated against the whole inventory, privacy-scanned and
// preflighted before the first byte is written, then published through the
// shared temp-then-rename path. And the renderer invents no progress: an
// unassessed card is shown as unassessed, a missing assessment makes an
// aggregate explicitly incomplete, and empty input has no distribution at all.
//
// TK-01Y adds documentation distributions across source types and scopes. A
// DQC declares its related constituents - grilling questions, Specs, ADRs,
// Tasks and other DQCs - by typed room-scoped identity, each one unit. The
// same arithmetic runs at DQC, landmark and Workbench scope over the distinct
// identities in that scope: a shared identity counts once, a mixed DQC is one
// item whose own children are never flattened in, and each aggregate exposes
// its numerator, denominator, evidence revision and rationale. Unknown
// identities and missing assessments make an aggregate incomplete; bad
// fractions and conflicting assessments make it invalid; nothing is dropped to
// make a total pass. Relations may form navigation cycles; a derived
// assessment is an arithmetic dependency, and a cycle of those is refused.
//
// Concurrency: `--expect-revision` refuses a write based on a stale read. It
// is a comparison, not a lock, and does not isolate two concurrent writers;
// see workbench/landmark-tracker/README.md.
import fs from 'node:fs';
import path from 'node:path';
import { assertSafeReadPath, assertSafeWritePath, collectionRelative, declaredTracker, findRoot, isMainModule, laneRelative, writeSafeFile, TRACKER_COLLECTIONS } from './workbench-paths.mjs';
import { allocateArtifactId, compareVisibleIds, visibleIdKey, visibleIdParts } from './visible-ids.mjs';
import { scanPrivacy } from './privacy.mjs';

// The exact ordered documentation-progress vocabulary. These describe concept
// and documentation progress, never Task status or implementation effort.
export const STEPS = Object.freeze(['Idea', 'Aligning', 'Confirmed', 'Mapped', 'Planned', 'Journey', 'Review', 'Verified']);
export const DQC_PREFIX = 'DQC';
export const LANDMARK_PREFIX = 'LMK';
// Schema 2 adds `related` constituents and `claims`. A schema 1 record from
// the foundation still loads and is upgraded on its next write.
export const DQC_SCHEMA = 'landmark-tracker/destination-question@2';
export const DQC_SCHEMA_V1 = 'landmark-tracker/destination-question@1';
export const LANDMARK_SCHEMA = 'landmark-tracker/landmark@1';
export const PROJECTION_SCHEMA = 'landmark-tracker/projection@1';
export const NO_LANDMARK = 'No landmark';
const QUESTIONS = 'destination-questions';
const LANDMARKS = 'landmarks';
const KINDS = Object.freeze({
  [QUESTIONS]: { prefix: DQC_PREFIX, schema: DQC_SCHEMA },
  [LANDMARKS]: { prefix: LANDMARK_PREFIX, schema: LANDMARK_SCHEMA }
});
const QUESTION_KEYS_V1 = ['answer', 'assessment', 'confirmation', 'expectedResult', 'history', 'id', 'landmarks', 'origin', 'question', 'result', 'revision', 'schema', 'sources', 'title', 'uncertainty'];
const QUESTION_KEYS = [...QUESTION_KEYS_V1, 'claims', 'related'];
// The source types that contribute to a distribution, in display order. Each
// declared constituent is one unit whatever its type; there is no supporting-
// reference exclusion and no effort weight.
export const SOURCE_TYPES = Object.freeze(['dqc', 'grilling-question', 'spec', 'adr', 'task']);
// Claim bookkeeping is not itself changed understanding.
const CLAIM_FIELDS = new Set(['claim', 'claim-evidence', 'claim-affected', 'schema']);
const LANDMARK_KEYS = ['history', 'id', 'importance', 'origin', 'revision', 'schema', 'summary', 'title'];
const NOTICE = 'Generated by workbench/tools/landmark-tracker.mjs rebuild from the destination-questions and landmarks records. Edit the records, never this file.';

export class TrackerRefusal extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.code = code;
    this.details = details;
  }
}

function refuse(code, message, details) {
  throw new TrackerRefusal(code, message, details);
}

function lstatOrNull(target) {
  try { return fs.lstatSync(target); } catch (error) {
    if (error.code === 'ENOENT') return null;
    throw error;
  }
}

function posixRelative(root, target) {
  return path.relative(root, target).split(path.sep).join('/');
}

// ---------------------------------------------------------------- discovery

function context(rootDir) {
  const root = path.resolve(rootDir);
  let declared;
  try { declared = declaredTracker(root); }
  catch (error) { refuse(error.code === 'invalid-tracker' ? 'invalid-manifest' : error.code ?? 'invalid-manifest', error.message); }
  if (!declared) refuse('tracker-undeclared', 'This room declares no Landmark Tracker root; add a landmarkTracker block to workbench/manifest.json (see workbench/landmark-tracker/README.md).');
  const trackerRoot = path.resolve(root, declared.root);
  const dirs = Object.fromEntries(TRACKER_COLLECTIONS.map(name => [name, path.resolve(root, declared.collections[name])]));
  for (const directory of [trackerRoot, ...Object.values(dirs)]) {
    try { assertSafeReadPath(root, directory); }
    catch (error) { refuse('unsafe-path', error.message); }
    const entry = lstatOrNull(directory);
    if (!entry) refuse('missing-collection', `${posixRelative(root, directory)} is declared but missing; create it as an ordinary directory.`);
    if (!entry.isDirectory()) refuse('unsafe-path', `${posixRelative(root, directory)} must be an ordinary directory.`);
  }
  return { root, declared, trackerRoot, dirs, projection: path.resolve(root, declared.projection) };
}

// --------------------------------------------------------------- validation

function isText(value) {
  return typeof value === 'string' && value.trim().length > 0 && value === value.trim();
}

function isToken(value) {
  return typeof value === 'string' && /^[^\s]+$/.test(value) && value.length <= 200;
}

function isStamp(value) {
  return typeof value === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/.test(value);
}

function isRevision(value) {
  return Number.isSafeInteger(value) && value >= 1;
}

function isPlainObject(value) {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function exactKeys(value, keys) {
  return isPlainObject(value) && JSON.stringify(Object.keys(value).sort()) === JSON.stringify([...keys].sort());
}

// A meaningful title names a concept: not blank, not padded, and not merely an
// identifier standing in for one.
function titleProblems(title, label) {
  if (!isText(title)) return [`${label} must be non-empty text without surrounding whitespace`];
  if (title.length > 200) return [`${label} must be at most 200 characters`];
  if (visibleIdParts(title)) return [`${label} must name the concept, not an identifier (${title})`];
  return [];
}

function sourceProblems(sources, label) {
  if (!Array.isArray(sources)) return [`${label} must be an array`];
  const problems = [];
  const seen = new Set();
  for (const source of sources) {
    if (!exactKeys(source, ['id', 'revision']) || !isToken(source.id) || !(source.revision === null || isToken(source.revision))) {
      problems.push(`${label} entries are {id, revision} with an identifier and a revision or null`);
      continue;
    }
    if (seen.has(source.id)) problems.push(`${label} repeats ${source.id}`);
    seen.add(source.id);
  }
  return problems;
}

function historyProblems(record) {
  const problems = [];
  if (!Array.isArray(record.history) || record.history.length === 0) return ['history must record at least the capture'];
  record.history.forEach((entry, index) => {
    if (!exactKeys(entry, ['at', 'changes', 'reason', 'revision'])) { problems.push(`history entry ${index + 1} must be {revision, at, reason, changes}`); return; }
    if (entry.revision !== index + 1) problems.push(`history entry ${index + 1} must carry revision ${index + 1}`);
    if (!isStamp(entry.at)) problems.push(`history entry ${index + 1} needs an ISO timestamp`);
    if (!isText(entry.reason)) problems.push(`history entry ${index + 1} needs a reason (why this changed)`);
    if (!Array.isArray(entry.changes) || entry.changes.length === 0 || entry.changes.some(change => !isPlainObject(change) || !isText(change.field))) problems.push(`history entry ${index + 1} must list its changes`);
  });
  if (record.history.at(-1)?.revision !== record.revision) problems.push('the last history entry must match the record revision');
  return problems;
}

// An assessment either states fractions over the vocabulary with a basis and
// evidence, or - for a DQC's own assessment only - is derived from its related
// items with a stated basis (an arithmetic dependency on them).
function assessmentProblems(assessment, revision, { allowDerived = false } = {}) {
  if (assessment === null) return [];
  if (allowDerived && isPlainObject(assessment) && Object.hasOwn(assessment, 'derived')) {
    if (!exactKeys(assessment, ['basis', 'derived', 'revision'])) return ['a derived assessment is {derived: "related", basis, revision}; it takes its evidence from the related items'];
    const problems = [];
    if (assessment.derived !== 'related') problems.push('a derived assessment derives from "related"');
    if (!isText(assessment.basis)) problems.push('a derived assessment needs a basis');
    if (!isRevision(assessment.revision) || assessment.revision > revision) problems.push('assessment revision must be a record revision');
    return problems;
  }
  if (!exactKeys(assessment, ['basis', 'contributions', 'evidence', 'revision'])) return ['assessment must be {contributions, basis, evidence, revision}'];
  const problems = [];
  const entries = isPlainObject(assessment.contributions) ? Object.entries(assessment.contributions) : null;
  if (!entries || entries.length === 0) problems.push('assessment contributions must name at least one step');
  else {
    for (const [step, fraction] of entries) {
      if (!STEPS.includes(step)) problems.push(`assessment step ${step} is not in the vocabulary ${STEPS.join(', ')}`);
      if (typeof fraction !== 'number' || !Number.isFinite(fraction) || fraction <= 0 || fraction > 1) problems.push(`assessment fraction for ${step} must be greater than 0 and at most 1`);
    }
    const total = entries.reduce((sum, [, fraction]) => sum + (typeof fraction === 'number' ? fraction : 0), 0);
    if (Math.abs(total - 1) > 1e-9) problems.push(`assessment fractions must sum to 1; they sum to ${total}`);
  }
  if (!isText(assessment.basis)) problems.push('assessment needs a basis stating how its fractions were judged');
  if (!Array.isArray(assessment.evidence) || assessment.evidence.length === 0 || assessment.evidence.some(item => !isText(item))) problems.push('assessment must name at least one piece of supporting evidence');
  if (!isRevision(assessment.revision) || assessment.revision > revision) problems.push('assessment revision must be a record revision');
  return problems;
}

// ------------------------------------------------------- typed identities
//
// A constituent is named by its type and its room-scoped identity. Spec, ADR
// and DQC identities compare as visible identities. A letter-bearing Task
// label is unique across the room; a legacy numeric Task label is unique only
// within its Spec, so it must be written Spec-qualified (S-00H/TK-003) and
// keeps those bytes. A grilling question keeps the label its notes use.

const TASK_FORM = /^(?:([A-Z][A-Z0-9]{0,15}-[0-9A-Za-z]+)\/)?([A-Z][A-Z0-9]{0,15}-[0-9A-Za-z]+)$/;

function taskParts(id) {
  const match = typeof id === 'string' ? TASK_FORM.exec(id) : null;
  if (!match) return null;
  const spec = match[1] ?? null;
  const task = match[2];
  if (visibleIdParts(task)?.prefix !== 'TK' || (spec && visibleIdParts(spec)?.prefix !== 'S')) return null;
  return { spec, task, numeric: /^[0-9]+$/.test(visibleIdParts(task).suffix) };
}

export function itemIdentityProblems(type, id) {
  if (!SOURCE_TYPES.includes(type)) return [`related type ${JSON.stringify(type)} is not one of ${SOURCE_TYPES.join(', ')}`];
  if (type === 'grilling-question') return typeof id === 'string' && /^[^\s@:]{1,200}$/.test(id) ? [] : [`grilling question ${JSON.stringify(id)} must be a label without spaces, @ or :`];
  if (type === 'task') {
    const parts = taskParts(id);
    if (!parts) return [`task ${JSON.stringify(id)} must be TK-... or Spec-qualified S-.../TK-...`];
    if (parts.numeric && !parts.spec) return [`legacy numeric Task label ${id} is scoped to its Spec; write it Spec-qualified, for example S-00H/${id}`];
    return [];
  }
  const prefix = { dqc: DQC_PREFIX, spec: 'S', adr: 'ADR' }[type];
  return visibleIdParts(id)?.prefix === prefix ? [] : [`${type} ${JSON.stringify(id)} must be a ${prefix}- identity`];
}

// The comparison key that decides whether two names are one identity.
export function itemKey(type, id) {
  if (type === 'grilling-question') return `${type}:${id}`;
  if (type === 'task') {
    const parts = taskParts(id);
    return parts.numeric ? `${type}:${visibleIdKey(parts.spec)}/${visibleIdKey(parts.task)}` : `${type}:${visibleIdKey(parts.task)}`;
  }
  return `${type}:${visibleIdKey(id)}`;
}

function relatedOf(record) {
  return record.related ?? [];
}

function claimsOf(record) {
  return record.claims ?? [];
}

function relatedProblems(record) {
  if (!Array.isArray(record.related)) return ['related must be a list of constituents'];
  const problems = [];
  const seen = new Map();
  record.related.forEach((entry, index) => {
    const label = `related entry ${index + 1}`;
    if (!exactKeys(entry, ['assessment', 'id', 'reason', 'revision', 'type'])) { problems.push(`${label} must be {type, id, revision, reason, assessment}`); return; }
    const identity = itemIdentityProblems(entry.type, entry.id);
    if (identity.length) { problems.push(...identity.map(problem => `${label}: ${problem}`)); return; }
    if (!(entry.revision === null || isToken(entry.revision))) problems.push(`${label}: revision must be null or a revision label`);
    if (!isText(entry.reason)) problems.push(`${label}: needs a reason (why it is related)`);
    const key = itemKey(entry.type, entry.id);
    if (entry.type === 'dqc' && visibleIdKey(entry.id) === visibleIdKey(record.id)) problems.push(`${label}: a DQC does not relate itself`);
    if (entry.type === 'dqc' && entry.assessment !== null) problems.push(`${label}: a related DQC carries its own assessment on its record; the relation holds none`);
    else problems.push(...assessmentProblems(entry.assessment, record.revision).map(problem => `${label}: ${problem}`));
    if (seen.has(key)) problems.push(`${label}: ${entry.type}:${entry.id} is already related as ${seen.get(key)}`);
    seen.set(key, `${entry.type}:${entry.id}`);
  });
  return problems;
}

const CLAIM_KEY = /^[A-Za-z][A-Za-z0-9-]{0,39}$/;

function claimProblems(record) {
  if (!Array.isArray(record.claims)) return ['claims must be a list'];
  const problems = [];
  const seen = new Set();
  const withinRecord = value => isRevision(value) && value <= record.revision;
  for (const claim of record.claims) {
    if (!exactKeys(claim, ['affected', 'evidence', 'key', 'revision', 'text']) || !CLAIM_KEY.test(claim.key ?? '')) { problems.push('each claim is {key, text, revision, evidence, affected} with a short key'); continue; }
    if (seen.has(claim.key)) problems.push(`claim ${claim.key} is repeated`);
    seen.add(claim.key);
    if (!isText(claim.text) || !withinRecord(claim.revision)) problems.push(`claim ${claim.key} needs text and the revision it was stated at`);
    if (!Array.isArray(claim.evidence) || claim.evidence.some(item => !exactKeys(item, ['ref', 'revision']) || !isText(item.ref) || !withinRecord(item.revision))) problems.push(`claim ${claim.key} evidence entries are {ref, revision}`);
    if (!Array.isArray(claim.affected) || claim.affected.some(item => !exactKeys(item, ['assessment', 'revision']) || !isText(item.assessment) || !withinRecord(item.revision))) problems.push(`claim ${claim.key} affected entries are {revision, assessment}`);
  }
  return problems;
}

export function validateQuestion(record) {
  const legacy = isPlainObject(record) && record.schema === DQC_SCHEMA_V1;
  const keys = legacy ? QUESTION_KEYS_V1 : QUESTION_KEYS;
  if (!exactKeys(record, keys)) return [`a DQC record has exactly the fields ${keys.join(', ')}`];
  const problems = [];
  if (record.schema !== DQC_SCHEMA && !legacy) problems.push(`schema must be ${DQC_SCHEMA}`);
  if (visibleIdParts(record.id)?.prefix !== DQC_PREFIX) problems.push(`id must be a ${DQC_PREFIX}- identity`);
  if (!isRevision(record.revision)) problems.push('revision must be a positive integer');
  problems.push(...titleProblems(record.title, 'title'));
  if (!isText(record.question)) problems.push('question must be non-empty text');
  if (!(record.answer === null || isText(record.answer))) problems.push('answer must be null (unanswered) or text');
  if (!(record.confirmation === null || (exactKeys(record.confirmation, ['basis', 'revision']) && isText(record.confirmation.basis) && isRevision(record.confirmation.revision)))) problems.push('confirmation must be null or {basis, revision}');
  if (!(record.expectedResult === null || (exactKeys(record.expectedResult, ['change', 'home', 'revision']) && isText(record.expectedResult.change) && (record.expectedResult.home === null || isText(record.expectedResult.home)) && isRevision(record.expectedResult.revision)))) problems.push('expectedResult must be null or {change, home, revision}; a home without an intended change is not an Expected result');
  if (!(record.result === null || (exactKeys(record.result, ['revision', 'summary']) && isText(record.result.summary) && isRevision(record.result.revision)))) problems.push('result must be null or {summary, revision}');
  if (!Array.isArray(record.uncertainty) || record.uncertainty.some(item => !isText(item)) || new Set(record.uncertainty).size !== record.uncertainty.length) problems.push('uncertainty must be a list of distinct texts');
  problems.push(...sourceProblems(record.sources, 'sources'));
  if (!Array.isArray(record.landmarks) || record.landmarks.some(id => visibleIdParts(id)?.prefix !== LANDMARK_PREFIX) || new Set(record.landmarks).size !== record.landmarks.length) problems.push(`landmarks must be a list of distinct ${LANDMARK_PREFIX}- identities`);
  problems.push(...assessmentProblems(record.assessment, record.revision, { allowDerived: !legacy }));
  if (!legacy) {
    problems.push(...relatedProblems(record));
    problems.push(...claimProblems(record));
    if (record.assessment && Object.hasOwn(record.assessment, 'derived') && Array.isArray(record.related) && record.related.length === 0) problems.push('a derived assessment needs at least one related item to derive from');
  }
  const origin = record.origin;
  if (!exactKeys(origin, ['at', 'question', 'revision', 'sources', 'title']) || origin.revision !== 1 || !isStamp(origin.at) || !isText(origin.question) || titleProblems(origin.title, 'origin title').length || sourceProblems(origin.sources, 'origin sources').length) problems.push('origin must preserve the captured {title, question, sources, revision: 1, at}');
  problems.push(...historyProblems(record));
  return problems;
}

export function validateLandmark(record) {
  if (!exactKeys(record, LANDMARK_KEYS)) return [`a landmark record has exactly the fields ${LANDMARK_KEYS.join(', ')}`];
  const problems = [];
  if (record.schema !== LANDMARK_SCHEMA) problems.push(`schema must be ${LANDMARK_SCHEMA}`);
  if (visibleIdParts(record.id)?.prefix !== LANDMARK_PREFIX) problems.push(`id must be a ${LANDMARK_PREFIX}- identity`);
  if (!isRevision(record.revision)) problems.push('revision must be a positive integer');
  problems.push(...titleProblems(record.title, 'title'));
  if (!isText(record.summary)) problems.push('summary must be non-empty text');
  if (!(record.importance === null || isText(record.importance))) problems.push('importance must be null or text');
  const origin = record.origin;
  if (!exactKeys(origin, ['at', 'revision', 'summary', 'title']) || origin.revision !== 1 || !isStamp(origin.at) || !isText(origin.summary) || titleProblems(origin.title, 'origin title').length) problems.push('origin must preserve the captured {title, summary, revision: 1, at}');
  problems.push(...historyProblems(record));
  return problems;
}

function validateKind(kind, record) {
  return kind === QUESTIONS ? validateQuestion(record) : validateLandmark(record);
}

// ---------------------------------------------------------------- inventory

function loadInventory(ctx) {
  const inventory = { [QUESTIONS]: new Map(), [LANDMARKS]: new Map(), keys: new Map() };
  for (const kind of TRACKER_COLLECTIONS) {
    const directory = ctx.dirs[kind];
    const entries = fs.readdirSync(directory, { withFileTypes: true }).sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
    for (const entry of entries) {
      // .gitkeep and interrupted `.write-*` temporaries are not records.
      if (entry.name.startsWith('.')) continue;
      const full = path.join(directory, entry.name);
      const relative = posixRelative(ctx.root, full);
      if (entry.isSymbolicLink()) refuse('unsafe-path', `${relative} is a symbolic link; records are ordinary files inside the room.`);
      if (!entry.isFile() || !entry.name.endsWith('.json')) refuse('invalid-record', `${relative} is not a flat JSON record; collections hold only <ID>.json files.`);
      if (fs.lstatSync(full).nlink > 1) refuse('unsafe-path', `${relative} is hard-linked; records are ordinary files.`);
      let record;
      try { record = JSON.parse(fs.readFileSync(full, 'utf8')); }
      catch (error) { refuse('invalid-record', `${relative} is not valid JSON: ${error.message}`); }
      const problems = validateKind(kind, record);
      if (problems.length) refuse('invalid-record', `${relative} is not a valid ${kind} record: ${problems.join('; ')}`, { record: relative, problems });
      if (path.basename(entry.name, '.json') !== record.id) refuse('invalid-record', `${relative} holds ${record.id}; a record file is named by its identity.`, { record: relative });
      const key = visibleIdKey(record.id);
      if (inventory.keys.has(key)) refuse('identity-collision', `${record.id} in ${relative} collides with ${inventory.keys.get(key)}; one identity names one record.`, { record: relative, other: inventory.keys.get(key) });
      inventory.keys.set(key, relative);
      inventory[kind].set(record.id, { record, relative, full });
    }
  }
  checkRelations(inventory);
  return inventory;
}

function checkRelations(inventory, starts = []) {
  for (const { record, relative } of inventory[QUESTIONS].values()) {
    for (const landmark of record.landmarks) {
      if (!inventory[LANDMARKS].has(landmark)) refuse('unknown-identity', `${record.id} (${relative}) links unknown landmark ${landmark}.`, { record: relative, landmark });
    }
  }
  const chain = dependencyCycle(inventory, starts);
  if (chain) refuse('dependency-cycle', `Derived assessments form an arithmetic dependency cycle: ${chain.join(' -> ')}. A derived DQC cannot depend, through other derived DQCs, on itself; assess one of them directly.`, { chain });
}

function questionIdsByKey(inventory) {
  return new Map([...inventory[QUESTIONS].keys()].map(id => [visibleIdKey(id), id]));
}

// Only a derived assessment depends on other records arithmetically: its
// edges run to the DQCs among its related items. Plain relations are
// navigation and may form cycles freely.
function dependencyCycle(inventory, starts) {
  const byKey = questionIdsByKey(inventory);
  const state = new Map();
  const stack = [];
  const visit = (id) => {
    state.set(id, 'active');
    stack.push(id);
    const record = inventory[QUESTIONS].get(id).record;
    if (record.assessment && Object.hasOwn(record.assessment, 'derived')) {
      for (const entry of relatedOf(record)) {
        const target = entry.type === 'dqc' ? byKey.get(visibleIdKey(entry.id)) : undefined;
        if (!target) continue;
        if (state.get(target) === 'active') return [...stack.slice(stack.indexOf(target)), target];
        if (!state.has(target)) {
          const found = visit(target);
          if (found) return found;
        }
      }
    }
    stack.pop();
    state.set(id, 'done');
    return null;
  };
  const order = [...starts.filter(id => inventory[QUESTIONS].has(id)), ...[...inventory[QUESTIONS].keys()].sort(compareVisibleIds)];
  for (const id of order) {
    if (state.has(id)) continue;
    const found = visit(id);
    if (found) return found;
  }
  return null;
}

function findRecord(inventory, id) {
  const key = visibleIdKey(id);
  for (const kind of TRACKER_COLLECTIONS) {
    for (const [recordId, entry] of inventory[kind]) if (visibleIdKey(recordId) === key) return { kind, ...entry };
  }
  return null;
}

// ---------------------------------------------------------- room resolution
//
// Specs, Tasks and ADRs resolve against the room's own declared lanes, in any
// lifecycle folder, by identity alone - the view never reads their status, so
// a done Task or an accepted ADR contributes only what an assessment says.
// DQCs resolve against the Tracker inventory. Grilling questions live in
// untracked notes a clone does not have, so they are taken as declared.

function directoryEntries(directory) {
  try { return fs.readdirSync(directory, { withFileTypes: true }).filter(entry => !entry.isSymbolicLink()); }
  catch (error) {
    if (error.code === 'ENOENT' || error.code === 'ENOTDIR') return [];
    throw error;
  }
}

function roomIndex(ctx) {
  if (ctx.roomIndex) return ctx.roomIndex;
  const index = { specs: new Map(), tasks: new Map(), adrs: new Set() };
  let specsRoot = null;
  let adrRoot = null;
  try { specsRoot = path.resolve(ctx.root, laneRelative(ctx.root, 'specs')); } catch { specsRoot = null; }
  try { adrRoot = path.resolve(ctx.root, collectionRelative(ctx.root, 'adr')); } catch { adrRoot = null; }
  if (specsRoot) {
    for (const folder of [specsRoot, path.join(specsRoot, 'retired')]) {
      for (const entry of directoryEntries(folder)) {
        const match = entry.isDirectory() ? /^(S-[0-9A-Za-z]+)(?:-|$)/.exec(entry.name) : null;
        if (!match || !visibleIdParts(match[1])) continue;
        const specKey = visibleIdKey(match[1]);
        const dir = path.join(folder, entry.name);
        index.specs.set(specKey, dir);
        const tasks = new Set();
        for (const taskFolder of [path.join(dir, 'tasks'), path.join(dir, 'tasks', 'retired')]) {
          for (const task of directoryEntries(taskFolder)) {
            const label = task.isDirectory() ? /^(TK-[0-9A-Za-z]+)$/.exec(task.name) : null;
            if (label) tasks.add(visibleIdKey(label[1]));
          }
        }
        // A legacy table-backed Spec names its Tasks in slice-table rows.
        let content = '';
        try { content = fs.readFileSync(path.join(dir, 'SPEC.md'), 'utf8'); } catch { content = ''; }
        for (const row of content.matchAll(/^\|\s*(TK-[0-9A-Za-z]+)\s*\|/gm)) tasks.add(visibleIdKey(row[1]));
        index.tasks.set(specKey, tasks);
      }
    }
  }
  if (adrRoot) {
    for (const folder of [adrRoot, path.join(adrRoot, 'proposed'), path.join(adrRoot, 'archive')]) {
      for (const entry of directoryEntries(folder)) {
        const match = entry.isFile() ? /^([0-9A-Za-z]{3,})-[a-z0-9]+(?:-[a-z0-9]+)*\.md$/.exec(entry.name) : null;
        if (match) index.adrs.add(visibleIdKey(`ADR-${match[1]}`));
      }
    }
  }
  ctx.roomIndex = index;
  return index;
}

export function resolveItem(ctx, inventory, type, id) {
  if (type === 'dqc') return questionIdsByKey(inventory).has(visibleIdKey(id)) ? 'tracker' : 'unknown';
  if (type === 'grilling-question' || !ctx) return 'declared';
  const index = roomIndex(ctx);
  if (type === 'spec') return index.specs.has(visibleIdKey(id)) ? 'room' : 'unknown';
  if (type === 'adr') return index.adrs.has(visibleIdKey(id)) ? 'room' : 'unknown';
  const parts = taskParts(id);
  const taskKey = visibleIdKey(parts.task);
  if (parts.spec) return index.tasks.get(visibleIdKey(parts.spec))?.has(taskKey) ? 'room' : 'unknown';
  return [...index.tasks.values()].some(tasks => tasks.has(taskKey)) ? 'room' : 'unknown';
}

// --------------------------------------------------------------- projection

function round(value) {
  const rounded = Math.round(value * 1e6) / 1e6;
  return Object.is(rounded, -0) ? 0 : rounded;
}

function stepMap(fill) {
  return Object.fromEntries(STEPS.map(step => [step, fill(step)]));
}

function typeRank(type) {
  const rank = SOURCE_TYPES.indexOf(type);
  return rank === -1 ? SOURCE_TYPES.length : rank;
}

function compareItems(left, right) {
  return typeRank(left.type) - typeRank(right.type) || compareVisibleIds(left.id, right.id) || (left.key < right.key ? -1 : left.key > right.key ? 1 : 0);
}

// Why a stated set of fractions cannot be counted, as registered codes.
function fractionCodes(contributions) {
  if (!isPlainObject(contributions)) return ['wrong-sum'];
  const codes = new Set();
  let total = 0;
  let finite = true;
  for (const [step, fraction] of Object.entries(contributions)) {
    if (!STEPS.includes(step)) codes.add('unknown-step');
    if (typeof fraction !== 'number' || !Number.isFinite(fraction)) { codes.add('nonfinite'); finite = false; continue; }
    if (fraction < 0) codes.add('negative');
    total += fraction;
  }
  if (finite && Math.abs(total - 1) > 1e-9) codes.add('wrong-sum');
  return [...codes];
}

const INVALID_MESSAGES = {
  nonfinite: 'a fraction is not a finite number',
  negative: 'a fraction is negative',
  'unknown-step': `a step is not in the vocabulary ${STEPS.join(', ')}`,
  'wrong-sum': 'the fractions do not sum to one',
  'conflicting-assessment': 'the same identity carries different assessments',
  'derived-invalid': 'the derivation includes an invalid item',
  'dependency-cycle': 'the derivation depends on itself'
};

// percentage = sum(contributions to step) / distinct item count * 100.
//
// `items` are {key?, type?, id, state?, assessment, ...}. Each distinct
// identity (by `canonical`, else `key`, else `id`) is one unit. An item is
// assessed (or derived) and adds its fractions; unassessed or unknown and
// stays in the denominator, making the aggregate incomplete; or invalid,
// which withholds the distribution. Nothing is ever dropped from `counted`.
export function distribution(items, { breakdown = true } = {}) {
  const unique = new Map();
  const conflicts = new Set();
  for (const raw of items) {
    const type = raw.type ?? (visibleIdParts(raw.id)?.prefix === DQC_PREFIX ? 'dqc' : 'item');
    const key = raw.key ?? `${type}:${raw.id}`;
    const item = { ...raw, type, key };
    const identity = raw.canonical ?? key;
    const prior = unique.get(identity);
    if (!prior) { unique.set(identity, item); continue; }
    const same = (prior.state ?? null) === (item.state ?? null) && JSON.stringify(prior.assessment?.contributions ?? null) === JSON.stringify(item.assessment?.contributions ?? null);
    if (!same) conflicts.add(identity);
  }
  const ordered = [...unique.entries()].sort(([, left], [, right]) => compareItems(left, right));
  if (ordered.length === 0) return { items: 0, denominator: 0, status: 'empty', counted: [], numerators: null, distribution: null, unassessed: [], unknown: [], invalid: [], bySourceType: {}, contributions: [] };
  const sums = stepMap(() => 0);
  const unassessed = [];
  const unknown = [];
  const invalid = [];
  const contributions = [];
  for (const [identity, item] of ordered) {
    let state = item.state ?? (item.assessment ? 'assessed' : 'unassessed');
    let codes = item.codes ?? [];
    if (conflicts.has(identity)) { state = 'invalid'; codes = ['conflicting-assessment']; }
    else if (state === 'derived-invalid') codes = codes.length ? codes : ['derived-invalid'];
    else if (state === 'assessed' || state === 'derived') {
      const problems = fractionCodes(item.assessment?.contributions);
      if (problems.length) { state = 'invalid'; codes = problems; }
    }
    const entry = {
      key: item.key,
      type: item.type,
      id: item.id,
      state,
      contributions: null,
      basis: item.assessment?.basis ?? null,
      evidence: item.assessment?.evidence ?? [],
      revision: item.assessment?.revision ?? null,
      holder: item.holder ?? null,
      itemRevision: item.itemRevision ?? null,
      ...(item.derivedFrom ? { derivedFrom: item.derivedFrom } : {})
    };
    if (state === 'assessed' || state === 'derived') {
      for (const [step, fraction] of Object.entries(item.assessment.contributions)) sums[step] += fraction;
      entry.contributions = Object.fromEntries(STEPS.filter(step => Object.hasOwn(item.assessment.contributions, step)).map(step => [step, round(item.assessment.contributions[step])]));
    } else if (state === 'invalid' || state === 'derived-invalid') {
      entry.codes = codes;
      invalid.push({ key: item.key, codes, problems: codes.map(code => INVALID_MESSAGES[code] ?? code) });
    } else if (state === 'unknown') unknown.push(item.key);
    else unassessed.push(item.key);
    contributions.push(entry);
  }
  const count = ordered.length;
  const status = invalid.length ? 'invalid' : unassessed.length || unknown.length ? 'incomplete' : 'complete';
  const types = SOURCE_TYPES.filter(type => ordered.some(([, item]) => item.type === type))
    .concat([...new Set(ordered.map(([, item]) => item.type))].filter(type => !SOURCE_TYPES.includes(type)).sort());
  const bySourceType = {};
  if (breakdown) {
    for (const type of types) {
      const subset = ordered.filter(([, item]) => item.type === type).map(([identity, item]) => ({ ...item, canonical: identity, ...(conflicts.has(identity) ? { state: 'invalid', codes: ['conflicting-assessment'] } : {}) }));
      const { items: typeItems, status: typeStatus, counted, numerators, distribution: shares } = distribution(subset, { breakdown: false });
      bySourceType[type] = { items: typeItems, status: typeStatus, counted, numerators, distribution: shares };
    }
  }
  const withheld = status === 'invalid';
  return {
    items: count,
    denominator: count,
    status,
    counted: ordered.map(([, item]) => item.key),
    numerators: withheld ? null : stepMap(step => round(sums[step])),
    distribution: withheld ? null : stepMap(step => round((sums[step] * 100) / count)),
    unassessed,
    unknown,
    invalid,
    bySourceType,
    contributions,
    ...(unassessed.length ? { unassessedPercent: round((unassessed.length * 100) / count) } : {}),
    ...(unknown.length ? { unknownPercent: round((unknown.length * 100) / count) } : {})
  };
}

function corrections(record) {
  return record.history.flatMap(entry => entry.changes
    .filter(change => change.field === 'correction')
    .map(change => ({ revision: entry.revision, text: change.to, reason: entry.reason })));
}

// Every distinct identity in the Workbench with its one effective
// contribution. A non-DQC identity takes the assessment its relations state;
// two different ones are a conflict, never a silent pick. A DQC takes its own
// record's assessment, or derives it from its related items.
function itemIndex(inventory, ctx) {
  const questions = [...inventory[QUESTIONS].values()].map(entry => entry.record).sort((a, b) => compareVisibleIds(a.id, b.id));
  const byKey = questionIdsByKey(inventory);
  const index = new Map();
  const touch = (type, id) => {
    const canonical = itemKey(type, id);
    if (!index.has(canonical)) {
      const resolvedId = type === 'dqc' && byKey.has(visibleIdKey(id)) ? byKey.get(visibleIdKey(id)) : id;
      index.set(canonical, { canonical, type, id: resolvedId, key: `${type}:${resolvedId}`, resolution: resolveItem(ctx, inventory, type, resolvedId), holders: [], relatedBy: [] });
    }
    return index.get(canonical);
  };
  for (const record of questions) touch('dqc', record.id);
  for (const record of questions) {
    for (const entry of relatedOf(record)) {
      const item = touch(entry.type, entry.id);
      if (!item.relatedBy.includes(record.id)) item.relatedBy.push(record.id);
      if (entry.type !== 'dqc') item.holders.push({ dqc: record.id, itemRevision: entry.revision, reason: entry.reason, assessment: entry.assessment });
    }
  }
  for (const item of index.values()) {
    if (item.type === 'dqc') continue;
    const stated = item.holders.filter(holder => holder.assessment);
    const distinct = [...new Set(stated.map(holder => JSON.stringify(holder.assessment.contributions)))];
    if (distinct.length > 1) Object.assign(item, { state: 'invalid', codes: ['conflicting-assessment'], problems: stated.map(holder => `${holder.dqc} states ${JSON.stringify(holder.assessment.contributions)} at revision ${holder.assessment.revision}`) });
    else if (item.resolution === 'unknown') Object.assign(item, { state: 'unknown', assessment: null });
    else if (stated.length) Object.assign(item, { state: 'assessed', assessment: stated[0].assessment, holder: stated[0].dqc, itemRevision: stated[0].itemRevision });
    else Object.assign(item, { state: 'unassessed', assessment: null, itemRevision: item.holders[0]?.itemRevision ?? null });
  }
  const evaluating = new Set();
  const evaluate = (item) => {
    if (item.state) return item;
    if (item.resolution === 'unknown') return Object.assign(item, { state: 'unknown', assessment: null });
    const record = inventory[QUESTIONS].get(item.id).record;
    if (!record.assessment) return Object.assign(item, { state: 'unassessed', assessment: null, holder: record.id });
    if (!Object.hasOwn(record.assessment, 'derived')) return Object.assign(item, { state: 'assessed', assessment: record.assessment, holder: record.id });
    if (evaluating.has(item.canonical)) return Object.assign(item, { state: 'derived-invalid', codes: ['dependency-cycle'], assessment: null, holder: record.id });
    evaluating.add(item.canonical);
    const inputs = relatedOf(record).map(entry => evaluate(index.get(itemKey(entry.type, entry.id))));
    evaluating.delete(item.canonical);
    const derived = distribution(inputs.map(asDistributionItem));
    const base = { holder: record.id, derivedFrom: derived.counted };
    if (derived.status === 'invalid') return Object.assign(item, base, { state: 'derived-invalid', codes: ['derived-invalid'], assessment: { basis: record.assessment.basis, evidence: [], revision: record.assessment.revision } });
    if (derived.status !== 'complete') return Object.assign(item, base, { state: 'derived-incomplete', assessment: { basis: record.assessment.basis, evidence: [], revision: record.assessment.revision } });
    const sums = stepMap(() => 0);
    for (const input of inputs) for (const [step, fraction] of Object.entries(input.assessment.contributions)) sums[step] += fraction;
    const contributions = Object.fromEntries(STEPS.filter(step => sums[step] > 0).map(step => [step, sums[step] / inputs.length]));
    return Object.assign(item, base, { state: 'derived', assessment: { contributions, basis: record.assessment.basis, evidence: [], revision: record.assessment.revision } });
  };
  for (const item of index.values()) evaluate(item);
  return index;
}

function asDistributionItem(item) {
  return {
    canonical: item.canonical,
    key: item.key,
    type: item.type,
    id: item.id,
    state: item.state,
    assessment: item.assessment ?? null,
    holder: item.holder ?? null,
    itemRevision: item.itemRevision ?? null,
    ...(item.codes ? { codes: item.codes } : {}),
    ...(item.derivedFrom ? { derivedFrom: item.derivedFrom } : {})
  };
}

// A DQC's scope is the card itself plus its declared constituents.
function scopeKeys(record) {
  return [itemKey('dqc', record.id), ...relatedOf(record).map(entry => itemKey(entry.type, entry.id))];
}

function aggregate(index, keys) {
  return distribution([...new Set(keys)].map(key => asDistributionItem(index.get(key))));
}

// Expand a card's lineage for navigation. A DQC met again on the current path
// is a navigation cycle and is marked, not expanded; one met elsewhere in the
// same tree is marked seen. Expansion never feeds the arithmetic.
function lineage(index, inventory, rootKey) {
  const seen = new Set();
  const node = (key, trail) => {
    const item = index.get(key);
    const base = { key: item.key, type: item.type, id: item.id };
    if (trail.has(key)) return { ...base, cycle: true };
    if (seen.has(key)) return { ...base, seen: true };
    seen.add(key);
    const expanded = { ...base, resolution: item.resolution, state: item.state };
    if (item.type !== 'dqc' || item.resolution === 'unknown') return expanded;
    const next = new Set(trail).add(key);
    expanded.related = relatedOf(inventory[QUESTIONS].get(item.id).record).map(entry => node(itemKey(entry.type, entry.id), next));
    return expanded;
  };
  return node(rootKey, new Set());
}

function claimView(record, claim) {
  const byRevision = new Map(record.history.map(entry => [entry.revision, entry]));
  const latestEvidence = Math.max(0, ...claim.evidence.map(item => item.revision));
  const latestAffected = Math.max(0, ...claim.affected.map(item => item.revision));
  return {
    key: claim.key,
    text: claim.text,
    revision: claim.revision,
    status: latestAffected > latestEvidence ? 'affected' : claim.evidence.length ? 'supported' : 'unsupported',
    evidence: claim.evidence,
    affectedBy: claim.affected.map((item) => {
      const entry = byRevision.get(item.revision);
      return { revision: item.revision, changed: [...new Set((entry?.changes ?? []).map(change => change.field).filter(field => !CLAIM_FIELDS.has(field)))], reason: entry?.reason ?? null, assessment: item.assessment };
    })
  };
}

function ownAssessment(record) {
  if (!record.assessment) return { state: 'unassessed' };
  return { state: Object.hasOwn(record.assessment, 'derived') ? 'derived' : 'assessed', ...record.assessment };
}

function questionCard(record, landmarks, index, inventory) {
  const titles = record.landmarks.map(id => landmarks.get(id).record.title);
  const claims = claimsOf(record).map(claim => claimView(record, claim));
  const self = index.get(itemKey('dqc', record.id));
  return {
    id: record.id,
    title: record.title,
    question: record.question,
    answer: record.answer,
    answered: record.answer !== null,
    confirmation: record.confirmation,
    expectedResult: record.expectedResult,
    result: record.result,
    uncertainty: record.uncertainty,
    landmarks: record.landmarks,
    landmarkDisplay: titles.length ? titles.join('; ') : NO_LANDMARK,
    assessment: ownAssessment(record),
    distribution: aggregate(index, scopeKeys(record)),
    related: relatedOf(record).map((entry) => {
      const item = index.get(itemKey(entry.type, entry.id));
      return { type: entry.type, id: entry.id, key: item.key, revision: entry.revision, reason: entry.reason, resolution: item.resolution, state: item.state, assessment: entry.assessment };
    }),
    relatedBy: self.relatedBy,
    lineage: lineage(index, inventory, self.canonical),
    claims,
    reconciliation: claims.filter(claim => claim.status === 'affected').map(claim => claim.key),
    sources: record.sources,
    origin: record.origin,
    corrections: corrections(record),
    revision: record.revision,
    history: record.history
  };
}

export function buildProjection(inventory, ctx = null) {
  const questions = [...inventory[QUESTIONS].values()].map(entry => entry.record).sort((a, b) => compareVisibleIds(a.id, b.id));
  const landmarks = [...inventory[LANDMARKS].values()].map(entry => entry.record).sort((a, b) => compareVisibleIds(a.id, b.id));
  const index = itemIndex(inventory, ctx);
  const cards = questions.map(record => questionCard(record, inventory[LANDMARKS], index, inventory));
  return {
    schema: PROJECTION_SCHEMA,
    notice: NOTICE,
    steps: [...STEPS],
    workbench: aggregate(index, questions.flatMap(scopeKeys)),
    landmarks: landmarks.map(record => {
      const members = questions.filter(question => question.landmarks.includes(record.id));
      return {
        id: record.id,
        title: record.title,
        summary: record.summary,
        importance: record.importance,
        questions: members.map(question => question.id),
        aggregate: aggregate(index, members.flatMap(scopeKeys)),
        origin: record.origin,
        revision: record.revision,
        history: record.history
      };
    }),
    noLandmark: { display: NO_LANDMARK, questions: questions.filter(question => question.landmarks.length === 0).map(question => question.id) },
    items: [...index.values()].sort(compareItems).map(item => ({
      key: item.key,
      type: item.type,
      id: item.id,
      resolution: item.resolution,
      state: item.state,
      ...(item.problems ? { problems: item.problems } : {}),
      holders: item.holders.map(holder => ({ dqc: holder.dqc, itemRevision: holder.itemRevision, reason: holder.reason, assessment: holder.assessment })),
      relatedBy: item.relatedBy
    })),
    reconciliation: cards.flatMap(card => card.claims.filter(claim => claim.status === 'affected').map((claim) => {
      const latest = claim.affectedBy.at(-1);
      return { dqc: card.id, claim: claim.key, revision: latest.revision, reason: latest.reason, assessment: latest.assessment };
    })),
    questions: cards
  };
}

function serialize(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

// ------------------------------------------------------------------- writes

function safeWrite(ctx, destination, content, options) {
  try { writeSafeFile(ctx.root, destination, content, options); }
  catch (error) {
    if (error.code === 'EEXIST') refuse('identity-collision', `${posixRelative(ctx.root, destination)} already exists; another writer published this identity first.`);
    throw error;
  }
}

function preflight(ctx, destination) {
  try { assertSafeWritePath(ctx.root, destination); }
  catch (error) { refuse('unsafe-path', error.message); }
}

// Validate everything, then write the changed records, then the projection.
// Nothing is written until every record, the whole resulting inventory, the
// privacy scan and every destination have passed.
function commit(ctx, inventory, changes) {
  const next = { [QUESTIONS]: new Map(inventory[QUESTIONS]), [LANDMARKS]: new Map(inventory[LANDMARKS]), keys: inventory.keys };
  const writes = [];
  for (const { kind, record, exclusive } of changes) {
    const problems = validateKind(kind, record);
    if (problems.length) refuse('invalid-record', `${record.id ?? 'the record'} would be invalid: ${problems.join('; ')}`, { problems });
    const content = serialize(record);
    const hits = scanPrivacy(content);
    if (hits.length) refuse('private-content', `${record.id} would carry private material (${[...new Set(hits.map(hit => hit.label))].join(', ')}); records are tracked in Git. Keep a safe reference instead.`, { labels: [...new Set(hits.map(hit => hit.label))] });
    const destination = path.join(ctx.dirs[kind], `${record.id}.json`);
    next[kind].set(record.id, { record, relative: posixRelative(ctx.root, destination), full: destination });
    writes.push({ destination, content, exclusive });
  }
  checkRelations(next, changes.map(change => change.record.id));
  const projection = serialize(buildProjection(next, ctx));
  for (const write of writes) preflight(ctx, write.destination);
  preflight(ctx, ctx.projection);
  for (const write of writes) safeWrite(ctx, write.destination, write.content, { exclusive: write.exclusive });
  safeWrite(ctx, ctx.projection, projection);
  return writes.map(write => posixRelative(ctx.root, write.destination));
}

function nowStamp() {
  return new Date().toISOString();
}

function asList(value) {
  if (value === undefined) return [];
  return Array.isArray(value) ? value : [value];
}

function parseSources(values) {
  return asList(values).map((raw) => {
    const at = raw.lastIndexOf('@');
    return at > 0 ? { id: raw.slice(0, at), revision: raw.slice(at + 1) || null } : { id: raw, revision: null };
  });
}

function allocate(inventory, prefix, requested) {
  if (requested !== undefined) {
    if (visibleIdParts(requested)?.prefix !== prefix) refuse('invalid-record', `--id ${requested} must be a ${prefix}- identity.`);
    const other = inventory.keys.get(visibleIdKey(requested));
    if (other) refuse('identity-collision', `${requested} is already held by ${other}; retitle or revise that record instead of recapturing it.`, { other });
    return requested;
  }
  // DQCs and landmarks are artifacts: the shared S-01W policy (uppercase,
  // width four, letter-bearing) with its default width.
  return allocateArtifactId(prefix, [...inventory.keys.values()].map(relative => path.basename(relative, '.json')));
}

function requireRevision(options, record) {
  const expected = Number(options['expect-revision']);
  if (record.revision !== expected) refuse('stale-revision', `${record.id} is at revision ${record.revision}, not ${options['expect-revision']}; reread it before writing.`, { current: record.revision });
}

// ----------------------------------------------------------------- commands

export function captureQuestion(rootDir, options = {}) {
  const ctx = context(rootDir);
  const inventory = loadInventory(ctx);
  const id = allocate(inventory, DQC_PREFIX, options.id);
  const at = nowStamp();
  const sources = parseSources(options.source);
  const record = {
    schema: DQC_SCHEMA,
    id,
    revision: 1,
    title: options.title,
    question: options.question,
    answer: options.answer ?? null,
    confirmation: null,
    expectedResult: null,
    result: null,
    uncertainty: asList(options.uncertainty),
    sources,
    landmarks: [],
    assessment: null,
    related: [],
    claims: [],
    origin: { title: options.title, question: options.question, sources, revision: 1, at },
    history: [{ revision: 1, at, reason: options.reason, changes: [{ field: 'captured' }] }]
  };
  const [written] = commit(ctx, inventory, [{ kind: QUESTIONS, record, exclusive: true }]);
  return { status: 'captured', id, revision: 1, record: written, projection: ctx.declared.projection };
}

export function addLandmark(rootDir, options = {}) {
  const ctx = context(rootDir);
  const inventory = loadInventory(ctx);
  const id = allocate(inventory, LANDMARK_PREFIX, options.id);
  const at = nowStamp();
  const record = {
    schema: LANDMARK_SCHEMA,
    id,
    revision: 1,
    title: options.title,
    summary: options.summary,
    importance: options.importance ?? null,
    origin: { title: options.title, summary: options.summary, revision: 1, at },
    history: [{ revision: 1, at, reason: options.reason, changes: [{ field: 'captured' }] }]
  };
  const [written] = commit(ctx, inventory, [{ kind: LANDMARKS, record, exclusive: true }]);
  return { status: 'captured', id, revision: 1, record: written, projection: ctx.declared.projection };
}

function parseAssessment(raw) {
  const contributions = {};
  for (const part of String(raw).split(',')) {
    const split = part.indexOf('=');
    const step = part.slice(0, split).trim();
    const value = split > 0 ? Number(part.slice(split + 1)) : NaN;
    if (split < 1 || !STEPS.includes(step)) refuse('invalid-record', `--assess step ${JSON.stringify(step || part)} is not in the vocabulary ${STEPS.join(', ')}; done and similar statuses never stand in for a step.`);
    if (Object.hasOwn(contributions, step)) refuse('invalid-record', `--assess names ${step} twice.`);
    contributions[step] = value;
  }
  // Store in vocabulary order so identical assessments serialize identically.
  return Object.fromEntries(STEPS.filter(step => Object.hasOwn(contributions, step)).map(step => [step, contributions[step]]));
}

const QUESTION_REVISIONS = ['title', 'question', 'answer', 'confirm', 'expected-change', 'expected-home', 'source', 'uncertainty', 'resolve-uncertainty', 'correction', 'assess', 'basis', 'evidence', 'claim', 'claim-evidence', 'affects'];

// A schema 1 record gains empty related and claims lists on its next write;
// the upgrade is recorded, and nothing it held is changed.
function upgrade(next, changes) {
  if (next.schema !== DQC_SCHEMA_V1) return;
  next.schema = DQC_SCHEMA;
  next.related = [];
  next.claims = [];
  changes.push({ field: 'schema', from: DQC_SCHEMA_V1, to: DQC_SCHEMA });
}

function keyedValues(values, flag) {
  return asList(values).map((raw) => {
    const split = raw.indexOf('=');
    const key = split > 0 ? raw.slice(0, split).trim() : '';
    const value = split > 0 ? raw.slice(split + 1).trim() : '';
    if (!CLAIM_KEY.test(key) || !value) refuse('invalid-record', `--${flag} takes KEY=TEXT with a short claim key; got ${JSON.stringify(raw)}.`);
    return { key, value };
  });
}

function assessmentFromOptions(options, revision, { allowDerived }) {
  if (options.assess === undefined) {
    if (options.basis !== undefined || options.evidence !== undefined) refuse('invalid-record', '--basis and --evidence describe an assessment; supply them with --assess.');
    return undefined;
  }
  if (String(options.assess).trim() === 'derived') {
    if (!allowDerived) refuse('invalid-record', 'Only a DQC\'s own assessment can be derived from its related items.');
    if (options.evidence !== undefined) refuse('invalid-record', 'A derived assessment takes its evidence from the related items; drop --evidence.');
    return { derived: 'related', basis: options.basis, revision };
  }
  return { contributions: parseAssessment(options.assess), basis: options.basis, evidence: asList(options.evidence), revision };
}
const LANDMARK_REVISIONS = ['title', 'summary', 'importance'];

function reviseQuestion(record, options, revision) {
  const next = structuredClone(record);
  const changes = [];
  for (const field of ['title', 'question', 'answer']) {
    if (options[field] !== undefined && options[field] !== record[field]) {
      changes.push({ field, from: record[field], to: options[field] });
      next[field] = options[field];
    }
  }
  if (options.confirm !== undefined) {
    next.confirmation = { basis: options.confirm, revision };
    changes.push({ field: 'confirmation', from: record.confirmation?.basis ?? null, to: options.confirm });
  }
  if (options['expected-change'] !== undefined || options['expected-home'] !== undefined) {
    next.expectedResult = {
      change: options['expected-change'] ?? record.expectedResult?.change,
      home: options['expected-home'] ?? record.expectedResult?.home ?? null,
      revision
    };
    changes.push({ field: 'expectedResult', from: record.expectedResult, to: next.expectedResult });
  }
  for (const source of parseSources(options.source)) {
    const existing = next.sources.find(item => item.id === source.id);
    if (!existing) {
      next.sources.push(source);
      changes.push({ field: 'source', from: null, to: source });
    } else if (existing.revision !== source.revision) {
      changes.push({ field: 'source', from: { ...existing }, to: source });
      existing.revision = source.revision;
    }
  }
  for (const text of asList(options.uncertainty)) {
    if (!next.uncertainty.includes(text)) { next.uncertainty.push(text); changes.push({ field: 'uncertainty', from: null, to: text }); }
  }
  for (const text of asList(options['resolve-uncertainty'])) {
    if (!next.uncertainty.includes(text)) refuse('invalid-record', `${record.id} records no uncertainty ${JSON.stringify(text)} to resolve.`);
    next.uncertainty = next.uncertainty.filter(item => item !== text);
    changes.push({ field: 'uncertainty', from: text, to: null });
  }
  for (const text of asList(options.correction)) changes.push({ field: 'correction', to: text });
  const assessment = assessmentFromOptions(options, revision, { allowDerived: true });
  if (assessment !== undefined) {
    next.assessment = assessment;
    changes.push({ field: 'assessment', from: record.assessment?.contributions ?? (record.assessment ? 'derived' : null), to: assessment.contributions ?? 'derived' });
  }
  upgrade(next, changes);
  reviseClaims(record, next, options, revision, changes);
  return { next, changes };
}

// Claims are the specific statements a card's documentation must carry. Each
// keeps every piece of evidence at the revision it was recorded. A revision
// that changes understanding names the claims it affects and assesses why;
// other claims, and other records related to this one, are left standing.
function reviseClaims(record, next, options, revision, changes) {
  const stated = keyedValues(options.claim, 'claim');
  const evidence = keyedValues(options['claim-evidence'], 'claim-evidence');
  const affects = keyedValues(options.affects, 'affects');
  if (!stated.length && !evidence.length && !affects.length) return;
  const existing = new Set(claimsOf(record).map(claim => claim.key));
  for (const { key, value } of stated) {
    const claim = next.claims.find(item => item.key === key);
    if (!claim) {
      next.claims.push({ key, text: value, revision, evidence: [], affected: [] });
      changes.push({ field: 'claim', claim: key, from: null, to: value });
    } else if (claim.text !== value) {
      changes.push({ field: 'claim', claim: key, from: claim.text, to: value });
      claim.text = value;
      claim.revision = revision;
    }
  }
  for (const { key, value } of evidence) {
    const claim = next.claims.find(item => item.key === key);
    if (!claim) refuse('invalid-record', `${record.id} has no claim ${key}; state it with --claim ${key}=TEXT first.`);
    claim.evidence.push({ ref: value, revision });
    changes.push({ field: 'claim-evidence', claim: key, to: value });
  }
  const understanding = changes.filter(change => !CLAIM_FIELDS.has(change.field));
  for (const { key, value } of affects) {
    if (!existing.has(key)) refuse('invalid-record', `${record.id} has no claim ${key} to assess as affected.`);
    if (evidence.some(item => item.key === key)) refuse('invalid-record', `${key} cannot be both affected by and re-evidenced in one revision; record the change first, then the new evidence.`);
    if (!understanding.length) refuse('invalid-record', `--affects ${key} names no changed understanding; change the title, question, answer, confirmation, Expected result, sources, uncertainty, corrections or assessment in the same revision.`);
    next.claims.find(item => item.key === key).affected.push({ revision, assessment: value });
    changes.push({ field: 'claim-affected', claim: key, assessment: value });
  }
}

function reviseLandmark(record, options) {
  const next = structuredClone(record);
  const changes = [];
  for (const field of LANDMARK_REVISIONS) {
    if (options[field] !== undefined && options[field] !== record[field]) {
      changes.push({ field, from: record[field], to: options[field] });
      next[field] = options[field];
    }
  }
  return { next, changes };
}

export function reviseRecord(rootDir, id, options = {}) {
  const ctx = context(rootDir);
  const inventory = loadInventory(ctx);
  const found = findRecord(inventory, id);
  if (!found) refuse('unknown-identity', `No Tracker record is named ${id}.`);
  const allowed = found.kind === QUESTIONS ? QUESTION_REVISIONS : LANDMARK_REVISIONS;
  const foreign = Object.keys(options).filter(key => [...QUESTION_REVISIONS, ...LANDMARK_REVISIONS].includes(key) && !allowed.includes(key));
  if (foreign.length) refuse('invalid-invocation', `${found.record.id} is a ${found.kind === QUESTIONS ? 'DQC' : 'landmark'}; it does not accept ${foreign.map(key => `--${key}`).join(', ')}.`);
  requireRevision(options, found.record);
  const revision = found.record.revision + 1;
  const { next, changes } = found.kind === QUESTIONS ? reviseQuestion(found.record, options, revision) : reviseLandmark(found.record, options);
  if (changes.length === 0) refuse('invalid-record', `This revision changes nothing in ${found.record.id}.`);
  next.revision = revision;
  next.history.push({ revision, at: nowStamp(), reason: options.reason, changes });
  commit(ctx, inventory, [{ kind: found.kind, record: next }]);
  return { status: 'revised', id: found.record.id, revision, record: found.relative, projection: ctx.declared.projection };
}

export function linkLandmark(rootDir, id, options = {}) {
  const ctx = context(rootDir);
  const inventory = loadInventory(ctx);
  const found = findRecord(inventory, id);
  if (!found || found.kind !== QUESTIONS) refuse('unknown-identity', `No DQC is named ${id}.`);
  requireRevision(options, found.record);
  const landmark = findRecord(inventory, options.landmark);
  if (!landmark || landmark.kind !== LANDMARKS) refuse('unknown-identity', `No landmark is named ${options.landmark}; capture it with add-landmark first.`);
  if (found.record.landmarks.includes(landmark.record.id)) refuse('invalid-record', `${found.record.id} is already linked to ${landmark.record.id}.`);
  const revision = found.record.revision + 1;
  const next = structuredClone(found.record);
  next.landmarks = [...next.landmarks, landmark.record.id].sort(compareVisibleIds);
  next.revision = revision;
  const changes = [{ field: 'landmarks', from: found.record.landmarks, to: next.landmarks }];
  upgrade(next, changes);
  next.history.push({ revision, at: nowStamp(), reason: options.reason, changes });
  commit(ctx, inventory, [{ kind: QUESTIONS, record: next }]);
  return { status: 'linked', id: found.record.id, landmark: landmark.record.id, revision, record: found.relative, projection: ctx.declared.projection };
}

function parseItem(raw) {
  const text = String(raw ?? '');
  const colon = text.indexOf(':');
  if (colon < 1) refuse('invalid-record', `--item takes TYPE:IDENTITY[@REVISION] with TYPE one of ${SOURCE_TYPES.join(', ')}; got ${JSON.stringify(text)}.`);
  const type = text.slice(0, colon);
  const rest = text.slice(colon + 1);
  const at = rest.lastIndexOf('@');
  const id = at > 0 ? rest.slice(0, at) : rest;
  const revision = at > 0 ? rest.slice(at + 1) || null : null;
  const problems = itemIdentityProblems(type, id);
  if (problems.length) refuse('invalid-record', problems.join('; '));
  return { type, id, revision };
}

// Declare (or re-assess) one related constituent of a DQC. The relation and
// any assessment of a non-DQC item live on this DQC's record - there is no
// second assessment store. A related DQC contributes its own assessment.
export function relateItem(rootDir, id, options = {}) {
  const ctx = context(rootDir);
  const inventory = loadInventory(ctx);
  const found = findRecord(inventory, id);
  if (!found || found.kind !== QUESTIONS) refuse('unknown-identity', `No DQC is named ${id}.`);
  requireRevision(options, found.record);
  const item = parseItem(options.item);
  if (item.type === 'dqc' && visibleIdKey(item.id) === visibleIdKey(found.record.id)) refuse('invalid-record', `${found.record.id} cannot relate itself.`);
  const revision = found.record.revision + 1;
  const assessment = assessmentFromOptions(options, revision, { allowDerived: false });
  if (item.type === 'dqc' && assessment !== undefined) refuse('invalid-record', `dqc:${item.id} carries its own assessment on its record; revise that DQC instead of assessing the relation.`);
  const next = structuredClone(found.record);
  const changes = [];
  upgrade(next, changes);
  const key = itemKey(item.type, item.id);
  const display = `${item.type}:${item.id}`;
  const existing = next.related.find(entry => itemKey(entry.type, entry.id) === key);
  if (!existing) {
    next.related.push({ type: item.type, id: item.id, revision: item.revision, reason: options.reason, assessment: assessment ?? null });
    changes.unshift({ field: 'related', from: null, to: { type: item.type, id: item.id, revision: item.revision } });
  } else {
    if (assessment !== undefined) {
      changes.unshift({ field: 'related-assessment', item: `${existing.type}:${existing.id}`, from: existing.assessment?.contributions ?? null, to: assessment.contributions });
      existing.assessment = assessment;
    }
    if (item.revision !== null && item.revision !== existing.revision) {
      changes.unshift({ field: 'related-revision', item: `${existing.type}:${existing.id}`, from: existing.revision, to: item.revision });
      existing.revision = item.revision;
    }
    if (!changes.some(change => change.field.startsWith('related'))) refuse('invalid-record', `${found.record.id} already relates ${existing.type}:${existing.id}; supply --assess or a new @REVISION to change it.`);
  }
  next.revision = revision;
  next.history.push({ revision, at: nowStamp(), reason: options.reason, changes });
  commit(ctx, inventory, [{ kind: QUESTIONS, record: next }]);
  const settled = existing ?? next.related.at(-1);
  return { status: 'related', id: found.record.id, item: { type: settled.type, id: settled.id, display: `${settled.type}:${settled.id}` }, requested: display, resolution: resolveItem(ctx, loadInventory(ctx), settled.type, settled.id), revision, record: found.relative, projection: ctx.declared.projection };
}

export function rebuildTracker(rootDir, options = {}) {
  const ctx = context(rootDir);
  const inventory = loadInventory(ctx);
  const content = serialize(buildProjection(inventory, ctx));
  const relative = ctx.declared.projection;
  if (options.check) {
    const entry = lstatOrNull(ctx.projection);
    const current = entry?.isFile() && !entry.isSymbolicLink() ? fs.readFileSync(ctx.projection, 'utf8') : null;
    if (current !== content) refuse('projection-drift', `${relative} does not match a rebuild from the records; run rebuild (never hand-edit the projection).`, { projection: relative });
    return { status: 'current', projection: relative };
  }
  preflight(ctx, ctx.projection);
  safeWrite(ctx, ctx.projection, content);
  return { status: 'rebuilt', projection: relative, questions: inventory[QUESTIONS].size, landmarks: inventory[LANDMARKS].size };
}

export function showTracker(rootDir, id) {
  const ctx = context(rootDir);
  const inventory = loadInventory(ctx);
  const projection = buildProjection(inventory, ctx);
  if (id === undefined) return { status: 'shown', tracker: projection };
  const found = findRecord(inventory, id);
  if (!found) refuse('unknown-identity', `No Tracker record is named ${id}.`);
  const view = found.kind === QUESTIONS
    ? projection.questions.find(card => card.id === found.record.id)
    : projection.landmarks.find(card => card.id === found.record.id);
  return { status: 'shown', id: found.record.id, kind: found.kind, record: found.record, view };
}

// ---------------------------------------------------------- human rendering

function percent(value) {
  return `${value}%`;
}

export function formatDistribution(aggregate) {
  if (aggregate.status === 'empty') return 'no items';
  const over = `over ${aggregate.items} item${aggregate.items === 1 ? '' : 's'} [${aggregate.status}]`;
  if (aggregate.status === 'invalid') return `distribution withheld: ${aggregate.invalid.map(entry => `${entry.key} (${entry.codes.join(', ')})`).join('; ')} ${over}`;
  const steps = STEPS.filter(step => aggregate.distribution[step] > 0).map(step => `${step} ${percent(aggregate.distribution[step])}`);
  const parts = steps.length ? steps : ['no assessed progress'];
  if (aggregate.unassessed?.length) parts.push(`unassessed ${percent(aggregate.unassessedPercent)} (${aggregate.unassessed.join(', ')})`);
  if (aggregate.unknown?.length) parts.push(`unknown ${percent(aggregate.unknownPercent)} (${aggregate.unknown.join(', ')})`);
  return `${parts.join(', ')} ${over}`;
}

function formatCard(card) {
  const lines = [`${card.id}  ${card.title}  (revision ${card.revision})`];
  lines.push(`  landmark: ${card.landmarkDisplay}`);
  lines.push(`  origin: "${card.origin.title}" from ${card.origin.sources.map(source => source.revision ? `${source.id}@${source.revision}` : source.id).join(', ') || 'no recorded source'}`);
  lines.push(`  answer: ${card.answered ? card.answer : 'unanswered'}`);
  if (card.expectedResult) lines.push(`  expected result: ${card.expectedResult.change}${card.expectedResult.home ? ` -> ${card.expectedResult.home}` : ''}`);
  lines.push(`  assessment: ${card.assessment.state === 'assessed' ? `${Object.entries(card.assessment.contributions).map(([step, fraction]) => `${step} ${fraction}`).join(', ')} (basis: ${card.assessment.basis})` : card.assessment.state === 'derived' ? `derived from related items (basis: ${card.assessment.basis})` : 'unassessed'}`);
  for (const entry of card.related ?? []) lines.push(`  related ${entry.key}${entry.revision ? `@${entry.revision}` : ''} [${entry.resolution}, ${entry.state}]: ${entry.reason}`);
  if (card.relatedBy?.length) lines.push(`  related by: ${card.relatedBy.join(', ')}`);
  if (card.distribution) lines.push(`  scope: ${formatDistribution(card.distribution)}`);
  for (const claim of card.claims ?? []) lines.push(`  claim ${claim.key} [${claim.status}]: ${claim.text}`);
  for (const entry of card.history) lines.push(`  r${entry.revision} ${entry.changes.map(change => change.field).join(', ')}: ${entry.reason}`);
  return lines.join('\n');
}

export function formatTracker(projection) {
  const lines = [`Workbench: ${formatDistribution(projection.workbench)}`];
  for (const landmark of projection.landmarks) lines.push(`${landmark.id}  ${landmark.title}: ${formatDistribution(landmark.aggregate)}; questions ${landmark.questions.join(', ') || 'none'}`);
  lines.push(`${projection.noLandmark.display}: ${projection.noLandmark.questions.join(', ') || 'none'}`);
  for (const card of projection.questions) lines.push(formatCard(card));
  for (const need of projection.reconciliation ?? []) lines.push(`reconciliation: ${need.dqc}#${need.claim} affected at r${need.revision}: ${need.assessment}`);
  return lines.join('\n');
}

function formatResult(command, result) {
  if (command === 'show') {
    if (result.tracker) return formatTracker(result.tracker);
    return result.kind === QUESTIONS ? formatCard(result.view) : `${result.view.id}  ${result.view.title}: ${formatDistribution(result.view.aggregate)}`;
  }
  if (command === 'rebuild') return `${result.status} ${result.projection}`;
  if (command === 'relate') return `${result.status} ${result.item.display} [${result.resolution}] to ${result.id} (revision ${result.revision}) in ${result.record}`;
  return `${result.status} ${result.id} (revision ${result.revision}) in ${result.record}`;
}

// --------------------------------------------------------------------- CLI

const MULTI = new Set(['source', 'uncertainty', 'resolve-uncertainty', 'correction', 'evidence', 'claim', 'claim-evidence', 'affects']);
const COMMON = ['path'];
const OPTIONS = Object.freeze({
  capture: { positional: false, flags: ['id', 'title', 'question', 'answer', 'source', 'uncertainty', 'reason'] },
  'add-landmark': { positional: false, flags: ['id', 'title', 'summary', 'importance', 'reason'] },
  revise: { positional: true, flags: ['expect-revision', 'reason', ...new Set([...QUESTION_REVISIONS, ...LANDMARK_REVISIONS])], required: ['expect-revision'] },
  link: { positional: true, flags: ['landmark', 'expect-revision', 'reason'], required: ['landmark', 'expect-revision'] },
  relate: { positional: true, flags: ['item', 'expect-revision', 'reason', 'assess', 'basis', 'evidence'], required: ['item', 'expect-revision'] },
  rebuild: { positional: false, flags: [], booleans: ['check'] },
  show: { positional: 'optional', flags: [] }
});

export const USAGE = 'Usage: landmark-tracker.mjs capture|add-landmark|revise ID|link ID|relate ID|rebuild|show [ID] [options] [--json] [--path DIR] (see workbench/landmark-tracker/README.md)';

export function parseArgs(argv) {
  const [command, ...rest] = argv;
  const spec = OPTIONS[command];
  if (!spec) throw new TrackerRefusal('invalid-invocation', USAGE);
  const accepted = [...spec.flags, ...COMMON];
  const booleans = new Set(['json', ...(spec.booleans ?? [])]);
  const options = {};
  let id;
  for (let index = 0; index < rest.length; index += 1) {
    const arg = rest[index];
    if (!arg.startsWith('--')) {
      if (!spec.positional || id !== undefined) throw new TrackerRefusal('invalid-invocation', `Unexpected argument ${arg}. ${USAGE}`);
      id = arg;
      continue;
    }
    const key = arg.slice(2);
    if (booleans.has(key)) { options[key] = true; continue; }
    if (!accepted.includes(key)) throw new TrackerRefusal('invalid-invocation', `${command} does not accept --${key}; it accepts ${[...accepted, ...booleans].map(name => `--${name}`).join(', ')}`);
    const value = rest[++index];
    if (value === undefined) throw new TrackerRefusal('invalid-invocation', `--${key} needs a value`);
    if (MULTI.has(key)) options[key] = [...(options[key] ?? []), value];
    else if (Object.hasOwn(options, key)) throw new TrackerRefusal('invalid-invocation', `--${key} was given twice`);
    else options[key] = value;
  }
  if (spec.positional === true && id === undefined) throw new TrackerRefusal('invalid-invocation', `${command} needs a record identity. ${USAGE}`);
  for (const key of spec.required ?? []) if (options[key] === undefined) throw new TrackerRefusal('invalid-invocation', `${command} requires --${key}`);
  if (options['expect-revision'] !== undefined && !/^[1-9][0-9]*$/.test(options['expect-revision'])) throw new TrackerRefusal('invalid-invocation', '--expect-revision must be a positive integer (the revision you read)');
  return { command, id, options };
}

export function runCommand(rootDir, command, id, options) {
  if (command === 'capture') return captureQuestion(rootDir, options);
  if (command === 'add-landmark') return addLandmark(rootDir, options);
  if (command === 'revise') return reviseRecord(rootDir, id, options);
  if (command === 'link') return linkLandmark(rootDir, id, options);
  if (command === 'relate') return relateItem(rootDir, id, options);
  if (command === 'rebuild') return rebuildTracker(rootDir, options);
  if (command === 'show') return showTracker(rootDir, id);
  throw new TrackerRefusal('invalid-invocation', USAGE);
}

if (isMainModule(import.meta.url)) {
  const argv = process.argv.slice(2);
  const json = argv.includes('--json');
  let command;
  try {
    const parsed = parseArgs(argv);
    command = parsed.command;
    const root = findRoot(parsed.options.path ?? process.cwd());
    const { path: _path, json: _json, ...options } = parsed.options;
    const result = runCommand(root, command, parsed.id, options);
    process.stdout.write(json ? `${JSON.stringify(result)}\n` : `${formatResult(command, result)}\n`);
  } catch (error) {
    const known = error instanceof TrackerRefusal;
    const failure = { status: 'blocked', error: { code: known ? error.code : 'tracker-failure', message: error.message, ...(known ? error.details : {}) } };
    if (json) process.stdout.write(`${JSON.stringify(failure)}\n`);
    else process.stderr.write(`blocked (${failure.error.code}): ${failure.error.message}\n`);
    process.exitCode = 1;
  }
}
